apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
  namespace: webapp
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/vagrant/classtask/nfsshare
    server: controller
