apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
  namespace: webapp
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pod_storage"
    type: Directory
