apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 # Cluster-internal service port
    targetPort: 80 # Container's port
    nodePort: 8888 # External port exposed on the node
